import { llms, loader } from 'fumadocs-core/source';
import { lucideIconsPlugin } from 'fumadocs-core/source/lucide-icons';
import { docsContentRoute, docsImageRoute, docsRoute } from './shared';
import { defineDocs } from 'fumadocs-mdx/macro';
import { metaSchema, pageSchema } from 'fumadocs-core/source/schema';
import { openapi } from './openapi';
import { renderOpenAPIPageMarkdown } from './openapi-markdown';

const docs = defineDocs({
  dir: 'content/docs',
  docs: {
    schema: pageSchema,
    postprocess: {
      includeProcessedMarkdown: true,
    },
  },
  meta: {
    schema: metaSchema,
  },
});

// See https://fumadocs.dev/docs/headless/source-api for more info
export const source = loader({
  baseUrl: docsRoute,
  source: docs.toFumadocsSource(),
  plugins: [lucideIconsPlugin(), openapi.loaderPlugin()],
});

export const docsLlms = llms(source, {
  renderPage: async (page) => {
    // Strip MDX comments (e.g. the "generated by Fumadocs" banner on endpoint pages).
    const processed = (await page.data.getText('processed')).replace(/\{\/\*[\s\S]*?\*\/\}/g, '');
    const body = [processed, renderOpenAPIPageMarkdown(page)]
      .filter((s) => s?.trim())
      .join('\n\n');

    return `# ${page.data.title} (${page.url})

${body}`;
  },
});
